site_name: Siddhi-Execution-Priority
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi Execution Priority: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.2-SNAPSHOT: api/4.0.2-SNAPSHOT.md
theme: material
